### ISSUE TITLE
Add `.npmrc` to `craco`-based templates for newer NPM

### ISSUE THREAD

**Issue by rassie** [pankod/superplate-core-plugins#251]
With current NPM version, `superplate` fails to install packages because `craco` hasn't been updated to support Webpack v5 and thus CRA v5. A solution is to use `npm install --legacy-peer-deps`, but then `superplate` has crashed already and it's also easy to forget.

A solution is to use a project-wide `.npmrc` like this: 
```
legacy-peer-deps=true
```
Maybe adding it to the templates until CRAv5 compatible `craco` is released would somewhat reduce the initial setup pain for new users.

**Comment by omeraplak** [comment]
Hey @rassie ,
Thank you! I've added `.npmrc` https://github.com/pankod/superplate-core-plugins/tree/master/refine-react/plugins/less

**Comment by rassie** [comment]
Thanks! Can confirm: with NPM 8.1.2 `npx superplate-cli -p refine-react tutorial` now runs through.
