### ISSUE TITLE
Keycloak auth not working, redirecting back to login

### ISSUE THREAD

**Issue by BojanKnezevic** [pankod/superplate-core-plugins#411]
Describe the bug

Hello, I have encountered a bug with Keycloak.

I have created a new app with npm create refine-app@latest, using Keycloak as auth provider.
The app builds fine, but upon trying to log in, I get redirected back to login page with url params. I will provide screenshots of the process.

1. Refine login page
![Screenshot from 2024-08-12 15-19-59](https://github.com/user-attachments/assets/e052a73c-9b5b-4293-92cd-1262097e35a2)

2. Keycloak login page
![Screenshot from 2024-08-12 15-20-15](https://github.com/user-attachments/assets/ffce8846-0fb8-4e1b-9e80-6a2a59685981)

3. Redirected back to Refine login page, with url params
![Screenshot from 2024-08-12 15-20-26](https://github.com/user-attachments/assets/44849f2d-cf96-4397-b6ab-e653b8b36ea1)

Just to note, this behavior is not observed when creating an example with npm create refine-app@latest -- --example auth-keycloak

Another side note, the login credentials in the documentation are not updated, username and password should be refine and not Refine.

Steps To Reproduce:
    1. Create a new app with npm create refine-app@latest, select Keycloak as auth provider, other options are not relevant
    2. Cd to project, run npm run dev
    3. Click 'Sign in' button
    4. Enter login credentials

Expected behavior:
Expected behavior is that with the provided credentials, a user should be logged in, instead, the user is redirected back to the login page with additional URL parameters.
Packages

"@react-keycloak/web": "^3.4.0",
"@refinedev/antd": "^5.37.4",
"@refinedev/cli": "^2.16.21",
"@refinedev/core": "^4.47.1",
"@refinedev/react-router-v6": "^4.5.5",
"@refinedev/simple-rest": "^5.0.1",

**Comment by ognjenAct** [comment]
Hey there, same issue here, I'm trying to setup keycloak and Refine, I came from here:
https://github.com/refinedev/refine/issues/6249

Any workaround on this topic?

**Comment by BojanKnezevic** [comment]
The issue is in **keyclosk-js** package versions, `npm create refine-app@latest` uses version "^20.0.3", and `npm create refine-app@latest -- --example auth-keycloak` uses version "^25.0.1".
